config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  namespace "admin" do
    get "/" => "dashboard#index"
    resources :regras
    resources :users
    resources :platforms
    resources :user_auths
    resources :channel_users
    resources :channels
    resources :default_channel_groups
    resources :admin_ranks
    resources :zones
  end

  namespace "dashboard" do
    get "/" => "dashboard#index"
    get "/profile" => "dashboard#profile"
    get "/settings" => "dashboard#settings"
    resources :channels
    resources :users
  end

  resources :channels, only: [:index, :new, :create]
  resources :feedback, only: [:index]
  resources :servidores, only: [:index]
  resources :users, only: [:index, :new, :create]

  get "staff" => "pages#staff"
  get "regras" => "pages#regras"
  get "rank" => "pages#rank"
  get "bans" => "pages#bans"

  get 'logout' => "auth#destroy"
  get 'login' => "auth#new"

  get 'auth/failure'
  post 'auth/steam/callback' => 'auth#steam'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/null_objects/user.rb
module NullObjects

    class User
      def name
        "Null User"
      end
  
      def image_url
        nil
      end
  
      def logged_in?
        false
      end
    end
    
  end
  
  

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  status     :string(255)
#  nickname   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord

    has_many :channel_user
    has_many :channel, through: :channel_user

    has_many :role_users
    has_many :roles, through: :role_users

    has_many :user_auth, :dependent => :destroy
    has_many :auth, through: :user_auth
    has_many :platform, through: :user_auth


    validates :name, presence: true
    validates :status, inclusion: { in: %w(good unverified banned),
        message: "%{value} is not a valid status" }
    

    
  scope :with_role, (lambda do |name|
    joins(:roles)
    .where(roles: { name: name })
    .distinct
  end)

  class << self
    def authenticate(args)
      where(args).first
    end
  end

  def logged_in?
    true
  end

  def role?(name)
    roles.where(name: name).any?
  end

  def admin?
    role?(:admin)
  end

  def user?
    role?(:user)
  end

  
  # def platforms?(name)
  #   platform.where(name: name).any?

  # end

  # def platform?
  #   platforms?(:steam)
  # end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseAdminController

    before_action :set_user, only: [:show, :edit, :update, :destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
      puts request.env['omniauth.auth']
    end


    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
      # user_params
    

      user_params = user_params

      params['status'] = 'good'
      
      # @user = User.new(@my_params)

      # respond_to do |format|
      #   if @user.save
          
        @user_auth = UserAuth.new(user_params)
        
        if auth_user.logged_in? 

          session[:current_user] = { 
            :nickname => @user['nickname'],
            :user_id => @user['id'],
          }

          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else 
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end

    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:name, :status, :nickname)
      end
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :user_params, only: [:show, :edit, :update, :destroy]


    def show
    end

    # GET /users/new
    def new
      @member = User.new
    end

    # POST /users
    # POST /users.json
    def create
      
      binding.pry
      
      user = user_params && UserService.fetch_user_from_auth(user_params, session[:auth_user_id])

      if auth_user.logged_in?

        session[:user_id] = user.id

        redirect_to "/login"
      else
        redirect_to "/users/new"
      end
    end

    def user_params
      params.require(:user).permit(:name, :nickname)
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :nickname %>
    <%= form.text_field :nickname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_table.html.haml
.kt-container.kt-grid__item.kt-grid__item--fluid
  / begin::Portlet
  .kt-portlet.kt-portlet--mobile
    .kt-portlet__body.kt-portlet__body--fit
      / begin: Datatable
      #kt_apps_user_list_datatable.kt-datatable.kt-datatable--default.kt-datatable--brand.kt-datatable--loaded{:style => ""}
        %table.kt-datatable__table{:style => "display: block;"}
          %thead.kt-datatable__head
            %tr.kt-datatable__row{:style => "left: 0px;"}
              %th.kt-datatable__cell--center.kt-datatable__cell.kt-datatable__cell--check{"data-field" => "RecordID"}
                %span{:style => "width: 20px;"}
                  %label.kt-checkbox.kt-checkbox--single.kt-checkbox--all.kt-checkbox--solid
                    %input{:type => "checkbox"}>/
                    \ 
                    %span
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-field" => "AgentName"}
                %span{:style => "width: 200px;"} User
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-field" => "Country"}
                %span{:style => "width: 140px;"} Country
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-field" => "ShipDate"}
                %span{:style => "width: 140px;"} Ship Date
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-autohide-disabled" => "false", "data-field" => "ShipName"}
                %span{:style => "width: 252px;"} Company
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-field" => "Status"}
                %span{:style => "width: 100px;"} Status
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-autohide-disabled" => "false", "data-field" => "Type"}
                %span{:style => "width: 110px;"} Type
              %th.kt-datatable__cell.kt-datatable__cell--sort{"data-autohide-disabled" => "false", "data-field" => "Actions"}
                %span{:style => "width: 80px;"} Actions
          %tbody.kt-datatable__body{:style => ""}
            %tr.kt-datatable__row{"data-row" => "0", :style => "left: 0px;"}
              %td.kt-datatable__cell--center.kt-datatable__cell.kt-datatable__cell--check{"data-field" => "RecordID"}
                %span{:style => "width: 20px;"}
                  %label.kt-checkbox.kt-checkbox--single.kt-checkbox--solid
                    %input{:type => "checkbox", :value => "1"}>/
                    \ 
                    %span
              %td.kt-datatable__cell{"data-field" => "AgentName"}
                %span{:style => "width: 200px;"}
                  .kt-user-card-v2
                    .kt-user-card-v2__pic
                      .kt-badge.kt-badge--xl.kt-badge--success N
                    .kt-user-card-v2__details
                      %a.kt-user-card-v2__name{:href => "#"} Nixie Sailor
                      %span.kt-user-card-v2__desc Developer
              %td.kt-datatable__cell{"data-field" => "Country"}
                %span{:style => "width: 140px;"} China CN
              %td.kt-datatable__cell{"data-field" => "ShipDate"}
                %span{:style => "width: 140px;"} 2/12/2018
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "ShipName"}
                %span{:style => "width: 252px;"}
                  .kt-user-card-v2
                    .kt-user-card-v2__pic
                      %img{:alt => "photo", :src => "/assets/client-logos/logo1.png"}/
                    .kt-user-card-v2__details
                      %a.kt-user-card-v2__name{:href => "#"} Gleichner, Ziemann and Gutkowski
                      %span.kt-user-card-v2__email Angular, React
              %td.kt-datatable__cell{"data-field" => "Status"}
                %span{:style => "width: 100px;"}
                  %span.btn.btn-bold.btn-sm.btn-font-sm.btn-label-success Success
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "Type"}
                %span{:style => "width: 110px;"}
                  %span.kt-badge.kt-badge--primary.kt-badge--dot>
                  \ 
                  %span.kt-font-bold.kt-font-primary Retail
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "Actions"}
                %span{:style => "overflow: visible; position: relative; width: 80px;"}
                  .dropdown
                    %a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md{"data-toggle" => "dropdown"}
                      %i.flaticon-more-1
                    .dropdown-menu.dropdown-menu-right
                      %ul.kt-nav
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-expand
                            %span.kt-nav__link-text View
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-contract
                            %span.kt-nav__link-text Edit
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-trash
                            %span.kt-nav__link-text Delete
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-mail-1
                            %span.kt-nav__link-text Export
            %tr.kt-datatable__row.kt-datatable__row--even{"data-row" => "1", :style => "left: 0px;"}
              %td.kt-datatable__cell--center.kt-datatable__cell.kt-datatable__cell--check{"data-field" => "RecordID"}
                %span{:style => "width: 20px;"}
                  %label.kt-checkbox.kt-checkbox--single.kt-checkbox--solid
                    %input{:type => "checkbox", :value => "2"}>/
                    \ 
                    %span
              %td.kt-datatable__cell{"data-field" => "AgentName"}
                %span{:style => "width: 200px;"}
                  .kt-user-card-v2
                    .kt-user-card-v2__pic
                      .kt-badge.kt-badge--xl.kt-badge--warning E
                    .kt-user-card-v2__details
                      %a.kt-user-card-v2__name{:href => "#"} Emelita Giraldez
                      %span.kt-user-card-v2__desc Developer
              %td.kt-datatable__cell{"data-field" => "Country"}
                %span{:style => "width: 140px;"} Indonesia ID
              %td.kt-datatable__cell{"data-field" => "ShipDate"}
                %span{:style => "width: 140px;"} 8/6/2017
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "ShipName"}
                %span{:style => "width: 252px;"}
                  .kt-user-card-v2
                    .kt-user-card-v2__pic
                      %img{:alt => "photo", :src => "/assets/client-logos/logo2.png"}/
                    .kt-user-card-v2__details
                      %a.kt-user-card-v2__name{:href => "#"} Rosenbaum-Reichel
                      %span.kt-user-card-v2__email Vue, Kendo
              %td.kt-datatable__cell{"data-field" => "Status"}
                %span{:style => "width: 100px;"}
                  %span.btn.btn-bold.btn-sm.btn-font-sm.btn-label-danger Done
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "Type"}
                %span{:style => "width: 110px;"}
                  %span.kt-badge.kt-badge--success.kt-badge--dot>
                  \ 
                  %span.kt-font-bold.kt-font-success Direct
              %td.kt-datatable__cell{"data-autohide-disabled" => "false", "data-field" => "Actions"}
                %span{:style => "overflow: visible; position: relative; width: 80px;"}
                  .dropdown
                    %a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md{"data-toggle" => "dropdown"}
                      %i.flaticon-more-1
                    .dropdown-menu.dropdown-menu-right
                      %ul.kt-nav
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-expand
                            %span.kt-nav__link-text View
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-contract
                            %span.kt-nav__link-text Edit
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-trash
                            %span.kt-nav__link-text Delete
                        %li.kt-nav__item
                          %a.kt-nav__link{:href => "#"}
                            %i.kt-nav__link-icon.flaticon2-mail-1
                            %span.kt-nav__link-text Export
        .kt-datatable__pager.kt-datatable--paging-loaded
          %ul.kt-datatable__pager-nav{:style => "display: none;"}
            %li
              %a.kt-datatable__pager-link.kt-datatable__pager-link--first.kt-datatable__pager-link--disabled{"data-page" => "1", :disabled => "disabled", :title => "First"}
                %i.flaticon2-fast-back
            %li
              %a.kt-datatable__pager-link.kt-datatable__pager-link--prev.kt-datatable__pager-link--disabled{"data-page" => "1", :disabled => "disabled", :title => "Previous"}
                %i.flaticon2-back
            %li{:style => ""}
            %li{:style => "display: none;"}
              %input.kt-pager-input.form-control{:title => "Page number", :type => "text"}/
            %li
              %a.kt-datatable__pager-link.kt-datatable__pager-link-number.kt-datatable__pager-link--active{"data-page" => "1", :title => "1"} 1
            %li{:style => ""}
            %li
              %a.kt-datatable__pager-link.kt-datatable__pager-link--next.kt-datatable__pager-link--disabled{"data-page" => "1", :disabled => "disabled", :title => "Next"}
                %i.flaticon2-next
            %li
              %a.kt-datatable__pager-link.kt-datatable__pager-link--last.kt-datatable__pager-link--disabled{"data-page" => "1", :disabled => "disabled", :title => "Last"}
                %i.flaticon2-fast-next
          .kt-datatable__pager-info
            .dropdown.bootstrap-select.kt-datatable__pager-size{:style => "width: 60px;"}
              %select.selectpicker.kt-datatable__pager-size{"data-selected" => "50", "data-width" => "60px", :tabindex => "-98", :title => "Select page size"}
                %option.bs-title-option{:value => ""}
                %option{:value => "10"} 10
                %option{:value => "20"} 20
                %option{:value => "30"} 30
                %option{:value => "50"} 50
                %option{:value => "100"} 100
              %button.btn.dropdown-toggle.btn-light{"aria-expanded" => "false", "aria-haspopup" => "listbox", "aria-owns" => "bs-select-1", "data-toggle" => "dropdown", :role => "combobox", :title => "Select page size", :type => "button"}
                .filter-option
                  .filter-option-inner
                    .filter-option-inner-inner 50
              .dropdown-menu
                #bs-select-1.inner.show{:role => "listbox", :tabindex => "-1"}
                  %ul.dropdown-menu.inner.show{:role => "presentation"}
            %span.kt-datatable__pager-detail Showing 1 - 40 of 40
      / end: Datatable
  / end::Portlet
  / begin::Modal
  #kt_datatable_records_fetch_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-dialog-centered{:role => "document"}
      .modal-content
        .modal-header
          %h5#exampleModalLabel.modal-title Selected Records
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"}
        .modal-body
          .kt-scroll.ps{"data-height" => "200", "data-scroll" => "true", :style => "height: 200px; overflow: hidden;"}
            %ul#kt_apps_user_fetch_records_selected
            .ps__rail-x{:style => "left: 0px; bottom: 0px;"}
              .ps__thumb-x{:style => "left: 0px; width: 0px;", :tabindex => "0"}
            .ps__rail-y{:style => "top: 0px; right: 0px;"}
              .ps__thumb-y{:style => "top: 0px; height: 0px;", :tabindex => "0"}
        .modal-footer
          %button.btn.btn-brand{"data-dismiss" => "modal", :type => "button"} Close
  / end::Modal
-# # <table>
-# #   <thead>
-# #     <tr>
-# #       <th>Name</th>
-# #       <th>Status</th>
-# #       <th>Nickname</th>
-# #       <th colspan="3"></th>
-# #     </tr>
-# #   </thead>

-# #   <tbody>
-# #     <% @users.each do |user| %>
-# #       <tr>
-# #         <td><%= user.name %></td>
-# #         <td><%= user.status %></td>
-# #         <td><%= user.nickname %></td>
-# #         <td><%= link_to 'Show', user %></td>
-# #         <td><%= link_to 'Edit', edit_user_path(user) %></td>
-# #         <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-# #       </tr>
-# #     <% end %>
-# #   </tbody>
-# # </table>

-# # <br>

-# # <%= link_to 'New User', new_user_path %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.haml
= render 'admin/users/table'

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/admin/users/show.html.haml
%h1 lool

-# <p id="notice"><%= notice %></p>

-# <p>
-#   <strong>Name:</strong>
-#   <%= @user.name %>
-# </p>

-# <p>
-#   <strong>Status:</strong>
-#   <%= @user.status %>
-# </p>

-# <p>
-#   <strong>Nickname:</strong>
-#   <%= @user.nickname %>
-# </p>

= link_to 'Edit', edit_admin_user_path(@user)
= link_to 'Back', admin_users_path 